### ISSUE TITLE
parsing indi with empty name

### ISSUE THREAD

**Issue by lucky-dd** [andy-z/ged4py#1]
* GEDCOM parser for Python version: ged4py-0.1.4
* Python version: 3.5
* Operating System: Windows 7 professional

### Description
Getting error by parsing of a GEDCOM-file with empty NAME-field of INDI

### What I Did

I tried to parse a GEDCOM-file exported from MyHeritage (Vers. 7) and by passing this few simple lines
```
	GEDParser = GedcomReader(source)	
	i = 0
	for record in GEDParser.records0("INDI"):
		print(i)
		i += 1
```

and got this error:
File "c:\Program Files\Python 3.5\lib\site-packages\ged4py\detail\name.py", line 33, in split_name
    given1, _, rem = name.partition("/")
AttributeError: 'NoneType' object has no attribute 'partition'

I found out, that this issue occurs, if there's an INDI witho no name in file exits, but although NAME is declared therein without following text like:
```
0 @I1@ INDI
1 RIN MH:I1
1 _UID 5AA81BB0875CC6533BC5FF485FE9D13B
1 _UPD 13 MAR 2018 19:42:56 GMT+1
1 NAME
1 SEX M
```
Maybe it's not allowed by GEDCOM guidelines, but I've really got this by MyHeritage 7 with a large database. I've tried to construct a similar case for testing, but actual MyHeritage export a GEDCOM-file without NAME-field fro such INDI and ged4py will work with it. But in my opinion egd4py should also work with file with empty NAME-entry.

I've attached test-case with 3 INDI, where the 1st has no name and my short python-program for testing.

[ged4py-Test.zip](https://github.com/andy-z/ged4py/files/1845184/ged4py-Test.zip)

**Comment by andy-z** [comment]
@lucky-dd, thanks a lot for very detailed report. I have added a protection for empty NAME record and pushed new tag v0.1.5 (should be on PyPI now too).
As for standards - GEDCOM standard is rather under-specified and every application decides how to interpret it on its own terms. Aa a result parsing GEDCOM is pretty much trial and error. For this particular case my reading of a standard says that if NAME record exists its value cannot be empty. Apparently MyHeritage reads the same text differently. In any case the protection is there now, for empty NAME you should receive the record that has all its components empty (i.e empty string, not `None`). Let me know if you still see a problem with the new version (or any other problem).

**Comment by andy-z** [comment]
No further comments, closing

**Comment by lucky-dd** [comment]
Hello, Andy.

> Von: Andy [mailto:notifications@github.com] 
> Gesendet: Montag, 26. März 2018 07:56
> An: andy-z/ged4py
> Cc: lucky-dd; Mention
> Betreff: Re: [andy-z/ged4py] parsing indi with empty name (#1)

> @lucky-dd, thanks a lot for very detailed report. I have added a protection for empty NAME record and pushed new tag v0.1.5 (should be on PyPI now too).
> As for standards - GEDCOM standard is rather under-specified and every application decides how to interpret it on its own terms. Aa a result parsing GEDCOM
> is pretty much trial and error. For this particular case my reading of a standard says that if NAME record exists its value cannot be empty. Apparently MyHeritage
> reads the same text > differently. In any case the protection is there now, for empty NAME you should receive the record that has all its components empty
> (i.e empty string, not None). Let me know if you still see a problem with the new version (or any other problem).

Sorry for my late answer and many thanks for your "fix for empty names exceptions"!
I haven't enough time until now to try your new version (meanwhile you've commited a few versions more I've even seen). But I'll use your library in next two weeks again with my ged-file with described issue and so I'm glad to work with a bugfixed version without need of work-around corrections in the GEDCOM-file.


Yours sincerely,
Maik Nicke
