### ISSUE TITLE
Adding more encoding than the actual ascii, ansel & utf8

### ISSUE THREAD

**Issue by Tuisto59** [andy-z/ged4py#11]
* GEDCOM parser for Python version: '0.1.11'
* Python version: 2.7
* Operating System: Ubuntu16.04

### Description

Accept other encoding than the actual ascii, utf8 and ansel

### Actually

They are many encoding and synonym that are actually exist in GEDCOM file in the CHAR line.
Tamura Jones explain it in his webpage here :
https://www.tamurajones.net/GEDCOMCharacterEncodings.xhtml

### What I Did

Because I have some file that are not from common software they use WINDOWS, or ANSI, or other kind of character set, to be more exhaustive as possible and according to the Tamura article, I update the parser.py function from :

in the parser.py - line 83
```
    gedcom_char_to_codec = {
        'ansel': 'gedcom',
    }
```

to
```
    gedcom_char_to_codec = {
        'ansel': 'gedcom',
        "unicode": "utf-16",
        "ibmpc": "cp437",
        "ibm": "cp437",
        "ibm-pc": "cp437",
        "oem": "cp437",
        "msdos": "cp850",
        "ibm dos": "cp850",
        "ms-dos": "cp850",
        "ansi": "cp1252",
        "windows": "cp1252",
        "ibm_windows": "cp1252",
        "cp1252": "cp1252",
        "iso-8859-1": "iso8859_1",
        "iso8859-1": "iso8859_1",
        "iso8859": "iso8859_1",
        "latin1": "iso8859_1",
        "macintosh": "mac_roman"
    }
```
to accept more encoding.

I will return if I see any side-effect of this change in my project :)

Tuisto

**Comment by andy-z** [comment]
@Tuisto59, thanks for report! I'll need to go through that page and try to understand it. Your change seems innocuous, I think it should be OK to add that but some unit tests for that should be nice to have too.

**Comment by andy-z** [comment]
PR #12 should fix that, also makes errors/warnings as suggested in Tamura's article. Unit tests are added for new functionality.
