### ISSUE TITLE
Improve support for dates.

### ISSUE THREAD

**Issue by andy-z** [andy-z/ged4py#14]
@Tuisto59 suggested to me in a private message that date support can be improved, which is certainly true. 

Areas of improvements:
- look at https://www.tamurajones.net/GEDCOMDatePhrases.xhtml and https://www.tamurajones.net/TheGEDCOMDATECase.xhtml
- alternative calendars (French revolutionary in particular)

`convertdate` Python package is suggested as an option for converting dates in different calendars.

**Comment by andy-z** [comment]
Several things to investigate:
- case sensitivity of the dates (as outlined in https://www.tamurajones.net/TheGEDCOMDATECase.xhtml), I think ed4py is already handles dates in a case-insensitive way, maybe just check it and/or add few test cases
- parsing of Gregorian dates, I am not sure that I'm doing right thing now for the format which has year in the form "<year>/<2digit>" (and I'm not sure what the right thing to for that yet)
- invalid date phrases (as in https://www.tamurajones.net/GEDCOMDatePhrases.xhtml), I don't realy want to go into that undefined territory, so I will probably just say I'm going to ignore the issue
- comparison of dates from different calendars, if there is a library like `convertdate` which can do that then I'll think about adding support, but I'm not going to implement that myself.

**Comment by andy-z** [comment]
There is more general issue - what should be a good Python-side representation of all possible GEDCOM date formats. My current interface is OK for the purpose of `ged2doc` but it may be worth thinking about generally useful interface too. Defining good interfaces is hard, especially for things as loose and under-determined as GEDCOM, still it may be worth investing some time into that.

**Comment by Tuisto59** [comment]
Hi Andy,

I wrote a function, with the help of Tamura Jones web pages, when I wrote Peregrination, my web application, adapted for my use, and with the help of the french revolutionar calendar, I wrote it to be the more systematic as possible, and can be surely improved, in this function, I focus on catching the date (AAAA format) to make range of date (for example when the user click on a town on the mark and popup show the range of extreme date for this town depending of the data in the gedcom) but can be used to convert date or any formating.

`def get_date(DATE):
    """
    extract the year according to the gedcom 5.5 standard
    DATE str()
    return set of year

    In this function, we focus only to get the year, but can be extrapolated to get the entire date
    """
    # This is all the GEDCOM tag that are used commonly for date
    indicators = ['CAL', 'EST', 'ABT', 'BEF', 'AFT', 'FROM', 'TO', 'BET', 'AND', 'INT']


    # DATE Patterns : can be in the form DD MMM YYYY , MMM YYYY, YYYY
    patterns_catchers = [('[0-9]{1,2} .* [0-9]{1,}', '[0-9]{1,2} .* ([0-9]{1,})'),
                         ('.* [0-9]{1,}', '.* ([0-9]{1,})'),
                         ('[0-9]{1,}', '([0-9]{1,})')
                         ]

    # control variable
    indicator = list()
    combination = False
    bc = str()

    # check if the date is Before Christ : B.C.
    if 'B.C.' in DATE:
        bc = ' B.C.'

    # check any indicator, store it in a list
    for i in indicators:
        if i in DATE:
            indicator += [i]

    # check if it a range format: FROM <date> TO <date> / BET <date> AND <date>
    # len = 0, no indicator, len = 1, indicator, len = 2 two indicator (range format)
    if len(indicator) > 1:
        combination = True
    elif len(indicator) == 1:
        indicator = indicator[0]
    else:
        indicator = str()

    # check the date pattern type depending of the indicator
    for pattern1, catcher1 in patterns_catchers:

        if indicator:
            if combination:
                # case when is it FROM ... TO and BET ... AND
                for pattern2, catcher2 in patterns_catchers:
                    # in case if the range accross B.C. to A.C.
                    for bc1, bc2 in [('', bc), (bc, ''), (bc, bc)]:
                        a, b = indicator
                        pattern = a + ' ' + pattern1 + bc1 + ' ' + b + ' ' + pattern2 + bc2
                        catcher = a + ' ' + catcher1 + bc1 + ' ' + b + ' ' + catcher2 + bc2
                        if re.match(pattern, DATE):
                            results = re.findall(catcher, DATE)
                            date1, date2 = results[0]
                            # print(u'{},{},{}'.format(DATE,date1,date2))
                            # converting the french republican date into a standard gregorian date
                            # more type like for "Hebrew" or "Islamic" calendar can be added depending of the "@#CALENDAR TYPE@"
                            if '@#DFRENCH R@' in DATE:
                                from convertdate import french_republican
                                date1 = str(french_republican.to_gregorian(int(date1), 1, 1)[0])
                                date2 = str(french_republican.to_gregorian(int(date2), 1, 1)[0])
                            return date1, date2
            else:
                # case when only one indicator is used
                pattern = indicator + ' ' + pattern1 + bc
                catcher = indicator + ' ' + catcher1 + bc
                if re.match(pattern, DATE):
                    results = re.findall(catcher, DATE)
                    date1 = results[0]
                    # print(u'{},{},{}'.format(DATE,date1,date2))
                    if '@#DFRENCH R@' in DATE:
                        from convertdate import french_republican
                        date1 = str(french_republican.to_gregorian(int(date1), 1, 1)[0])
                    return date1, date1
        else:
            # No indicator used
            pattern = pattern1 + bc
            catcher = catcher1 + bc
            if re.match(pattern, DATE, re.UNICODE):
                results = re.findall(catcher, DATE, re.UNICODE)
                date1 = results[0]
                if '@#DFRENCH R@' in DATE:
                    from convertdate import french_republican
                    date1 = str(french_republican.to_gregorian(int(date1), 1, 1)[0])
                # print(DATE,date1,date1)
                return date1, date1
    # nothing have been catchec so return None
    # print(DATE,None,None)
    return False, False`

Et voilà !

Hope this can be helpfull

Tuisto59

**Comment by andy-z** [comment]
@Tuisto59, sorry it took me too long to find time for this. I have made a bunch of changes which I think should solve the issues mentioned above. I'm ready to merge all of that but I would appreciate any input for these changes. Could you have a quick look at the pull request #17, in particular two files `date.py` and `calendar.py`, to see if that makes sense or do I need to add anything else? Description on PR is a quick summary of all changes.

**Comment by andy-z** [comment]
@Tuisto59, I have also built docs for that branch if you want to look at that: https://ged4py.readthedocs.io/en/issues-14/
