### ISSUE TITLE
Enhancement Sub_tags with no list of tags ... 

### ISSUE THREAD

**Issue by ukgenes** [andy-z/ged4py#38]
* GEDCOM parser for Python version:
* Python version:
* Operating System:

### Description

Issue sub_records returns all but cannot "follow"
Sub tags requires a list of tags

### What I Did

Modified sub_tags to process no tags ...
    records = [x for x in record.sub_records if ((x.tag in tags) | (len(tags) == 0))]

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by andy-z** [comment]
@ukgenes, new release 0.4.3 (I have just pushed it o PyPI) extends `sub_tags()` behavior. If you do not pass any tags then it will return all direct sub-tags of a record, expanding pointer records if `follow` keyword argument is True (default).
